from .serializer_base_shoetener import ShortenerBaseSerializer

from .serializer_shortener_list import ShortenerListSerializer
from .serializer_shortener_detail import ShortenerDetailSerializer
from .serializer_shortener_create_updat import ShortenerCreateUpdateSerializer


from .serializer_category_list import CategoryListSerializer
from .serializer_category_detail import CategoryDetailSerializer