version: '3.3'

services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ShortLink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: 'redis:latest'
    container_name: 'redis_short_link'
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      -

volumes:
  postgres-data:
  redis-data: