# Generated by Django 4.1.7 on 2023-03-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('long_url', models.URLField(verbose_name='Long URL')),
                ('short', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Short')),
                ('password', models.CharField(blank=True, max_length=15, null=True, verbose_name='Password')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expired Time')),
                ('QR_code', models.ImageField(blank=True, null=True, upload_to='shortener/short_urls/QR', verbose_name='QR Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortener', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Shortener',
                'verbose_name_plural': 'Shortener',
            },
        ),
    ]
