# Generated by Django 4.1.7 on 2023-03-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortener', to='shortener.category', verbose_name='Category'),
        ),
    ]
