# Generated by Django 4.1.7 on 2023-03-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_shortener_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortener', to='shortener.category', verbose_name='Category'),
        ),
    ]
