# Generated by Django 4.1.7 on 2023-03-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0008_alter_category_status_alter_shortener_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('ip', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='IP')),
                ('os', models.CharField(max_length=200, verbose_name='os')),
                ('time_click', models.DateTimeField(auto_now_add=True, verbose_name='time click')),
                ('browser', models.CharField(max_length=200, verbose_name='Browser')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('language', models.CharField(max_length=200, verbose_name='Language')),
                ('shortener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='shortener.shortener', verbose_name='Shortener')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ('-time_click',),
            },
        ),
    ]
