# Generated by Django 4.1.7 on 2023-03-30 15:09

import apps.statistic.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='ip',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, validators=[apps.statistic.validator.IpChecker], verbose_name='IP'),
        ),
    ]
