# Generated by Django 4.1.7 on 2023-03-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_statistic_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='country',
        ),
    ]
