# Generated by Django 4.1.7 on 2023-03-31 11:46

import apps.statistic.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_remove_statistic_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='ip',
            field=models.CharField(max_length=45, validators=[apps.statistic.validator.IpChecker], verbose_name='IP'),
        ),
    ]
